### PR TITLE
Fix #57, Use MSG APIs

### LINKED ISSUE #57: Remove dependencies on deprecated SB APIs
**Is your feature request related to a problem? Please describe.**
SB APIs deprecated in nasa/cFE#777

**Describe the solution you'd like**
Update to use MSG module.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Replaces deprecated SB API's with MSG
Fix #57

**Testing performed**
Built and ran, enabled telemetry, checked noops

**Expected behavior changes**
None

**System(s) tested on**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions: Bundle main + this commit

**Additional context**
nasa/cFE#777

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 2020-11-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-November-04-2020) 
- Expected all union declared in the message library with CFE_Msg_msg_t
- Suggest that all three unions are declared together, @jphickey or @skliper submit a new issue for this

**Comment by skliper** [comment]
75ae384 - Fixed whitespace.

**Comment by astrogeco** [comment]
> [CCB 2020-11-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-November-04-2020)
> 
>     * Expected all union declared in the message library with CFE_Msg_msg_t
> 
>     * Suggest that all three unions are declared together, @jphickey or @skliper submit a new issue for this

@jphickey did you open the issue mentioned above?

**Comment by astrogeco** [comment]
@skliper can you open the issue referenced above?

**Comment by skliper** [comment]
> @skliper can you open the issue referenced above?

See nasa/cFE#1009

**Pull request merged**
