### PR TITLE
Fix #71, Add CodeQL analysis to workflow

### LINKED ISSUE #71: Add CodeQL analysis to workflow
**Is your feature request related to a problem? Please describe.**
CodeQL analysis not implemented in submodules

**Describe the solution you'd like**
Add so alerts are generated on pull requests to submodules

**Describe alternatives you've considered**
None

**Additional context**
CodeQL is run at the bundle (nasa/cFS) level, but link to code in submodules doesn't work.

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Fix #71 - adds CodeQL analysis

Differences from bundle - path theoretically limited to ci_lab, has timeout, and "security and quality", and only does the build (run not necessary for codeql analysis)

**Testing performed**
Ran on fork

**Expected behavior changes**
Adds Code QL analysis on push to main and pull requests (to main)

**System(s) tested on**
CI

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by ArielSAdamsNASA** [comment]
For some reason there is one warning presented in the workflow:
>1 issue was detected with this workflow: Please make sure that every branch in on.pull_request is also in on.push so that Code Scanning can compare pull requests against the state of the base branch.

Also when viewing the code scanning results, it shows results outside of the ci_lab path as seen below. For example, it shows errors for osal. 
image

**Comment by skliper** [comment]
@ArielSAdamsNASA I'm wondering if the error is because the analysis hasn't been run in main yet.  I tried runs on all branches for push/pull and saw the same warning.  Maybe it will go away?  For OSAL results - I'm not seeing the same thing.  Shows up as "This branch hasn't been scanned yet" for me on nasa/ci_lab main branch.  Which branch were you on?

**Comment by ArielSAdamsNASA** [comment]
> For OSAL results - I'm not seeing the same thing. Shows up as "This branch hasn't been scanned yet" for me on nasa/ci_lab main branch. Which branch were you on?

I was also on the nasa/ci_lab main branch. I ran the analysis again this morning and noticed that the OSAL results now have "(Test)" in the title. As long as it works locally for you, it should perform the same once implemented. 

image

**Review by ArielSAdamsNASA — APPROVED** [review]

**Comment by skliper** [comment]
@ArielSAdamsNASA Now I'm seeing the warnings... seems I have the path exclusions set up incorrectly, I'll try to fix!

**Comment by skliper** [comment]
Updates - made it only build ci (so it only reports CI errors), also embedded queries in workflow instead of separate config file

**Review by ArielSAdamsNASA — APPROVED** [review]

**Pull request merged**
